import { Box } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { createContext, useMemo, useState } from "react";
import styles from "../../../styles/Home.module.scss";
import AppBar from "../AppBar";
import { Drawer } from "../Drawer";
import GlobalContext from "../Drawer/GlobalContext";
import SearchField from "../SearchField";

type Props = {
  title: string;
  children?: JSX.Element | JSX.Element[];
};

const drawerWidth = 256;

const Home = ({ children, title, ...props }: Props) => {
  const [open, setOpen] = useState(true);
  const value = useMemo(() => ({ open, setOpen }), [open]);

  return (
    <GlobalContext.Provider value={value}>
      <div className={styles.container}>
        <Head>
          <title>Compal - {title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box
          sx={{
            width: "100%",
            display: "flex",
          }}
          >
          <AppBar />
          <Drawer />
          <Box
            component="main"
            sx={{
              // width: `calc(100% - ${drawerWidth}px)`,
              minHeight: "100vh",
              // overflowY: 'scroll',
              marginTop: 10,
              background: "#F5F7FB",
              flexGrow: 1,
              pt: 2,
              px: 5,
              pb: 5,
            }}
          >
            <SearchField />
            {children && children}
          </Box>
        </Box>
      </div>
    </GlobalContext.Provider>
  );
};

export default Home;
