import { Box, CssBaseline } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { createContext, useMemo, useState } from "react";
import styles from "../../../styles/Home.module.scss";
import AppBar from "../AppBar";
import { Drawer } from "../Drawer";
import DrwaerContext from "../Drawer/DrawerContext";
type Props = {
  title: string;
  children?: JSX.Element | JSX.Element[];
};

const drawerWidth = 256;



const Home = ({ children, title, ...props }: Props) => {
  const [open, setOpen] = useState(true);
  const value = useMemo(
    () => ({ open, setOpen }), 
    [open]
  );
  
  return (
    <DrwaerContext.Provider value={value}>
    <div className={styles.container}>
      <Head>
        <title>Compal - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          width: "100%",
          background: "yellow",
          display: "flex",
        }}
      >
          <CssBaseline />
          <AppBar/>
        <Drawer  />
        <Box
        component="main"
        sx={{
          // width: `calc(100% - ${drawerWidth}px)`,
          height: "calc(100vh)",
          background: "#F5F7FB",
          flexGrow: 1,
          px: 5,
        }}
      >
        {children && children}
        </Box>
        
      </Box>
    </div>
    </DrwaerContext.Provider>
  );
};

export default Home;
