import { Box, CssBaseline } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.scss";
import { Drawer } from "../components/Drawer";
type Props = {
  title: string;
  children: JSX.Element;
};

const Home = ({ children, title, ...props }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Compal - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Drawer />
      <Box
        sx={{
          width: "100%",
          background: "yellow",
          display: "flex",
        }}
      >
        <CssBaseline />
        {children}
      </Box>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
